regions= [
    'north america',
    'south america',
    'middle east',
    'asia'
]

cities= {
    1: 'Atlanta',
    2: 'Chicago',
    3: 'Montreal',
    4: 'Washington',
    5: 'New York',
    6: 'San Francisco',
    7: 'New York',
    8: 'London',
    9: 'Madrid',
    10: 'Paris',
    11: 'St. Petersburg',
    12: 'Milan',
    13: 'Los Angeles',
    14: 'Mexico City',
    15: 'Miami',
    16: 'Bogata',
    17: 'Lima',
    18: 'Santiago',
    19: 'Buenos Aires',
    20: 'Sao Paulo',
    21: 'Lagos',
    22: 'Kinshasa',
    23: 'Johannesburg',
    24: 'Kartoum',
    25: 'Cairo',
    26: 'Algiers',
    27: 'Istanbul',
    28: 'Baghdad',
    29: 'Moscow',
    30: 'Tehran',
    31: 'Karachi',
    32: 'Dalhi',
    33: 'Mumbai',
    34: 'Rivach',
    35: 'Chennai',
    36: 'Kolkata',
    37: 'Beijing',
    38: 'Seoul',
    39: 'Shanghai',
    40: 'Tokyo',
    41: 'Osaka',
    42: 'Taipei',
    43: 'Bangkok',
    44: 'Hong Kong',
    45: 'Ho Chi Mihn City',
    46: 'Jakarta',
    47: 'Manila',
    48: 'Sydney'
}
print(cities)